project:
  type: book

execute:
  freeze: auto

book:
  title: "Fundamentals of Research Data Management"
  author: "Christine Staiger, Neha Moopen"
  date: last-modified
  sidebar:
    tools:
      - icon: github
        menu:
          - text: Source code
            url:  https://github.com/chStaiger/rdm-fundamentals
          - text: Report an issue
            url:  https://github.com/chStaiger/rdm-fundamentals/issues
  chapters:
    - index.qmd
    - definitions.qmd
    - data-lifecycle.qmd
    - part: "THE HOLY TRINITY OF RDM"
      chapters:
      - data-object.qmd
      - files.qmd
      - metadata.qmd
      - pids.qmd
    - part: "COMPONENTS OF RDM INFRASTRUCTURE"
      chapters:
      - rdm-infra-intro.qmd
      - data-repositories.qmd
      - metadata-portals.qmd
      - pid-services.qmd
      - rdm-platform.qmd
    - infrastructure-design.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    number-sections: false
    mermaid:
      theme: forest


